Swift 3 Result of call to (_:parameters:completionHandler:)' is unused warning and Braced block of statements is an unused closure error
I have working Swift.2.3 project but when I build and convert it to Swift3 it gives me: Result of call to (_:parameters:completionHandler:)' is unused warning. Warning. My clear working codes under below, how can I convert them with true way? InmyClass;  private func getMoviesDirectorsFromJSON(jsonData: NSData) throws -> [Director] { var directors = [Director]() do { if let jsonObject = try NSJSONSerialization.JSONObjectWithData(jsonData, options: .AllowFragments) as? [String: AnyObject], jsonArray = jsonObject["Actors"] as? [[String: AnyObject]] { for i in jsonArray { var properties = [String: AnyObject]() properties[directorJSONKeys.id] = i[directorJSONKeys.id] properties[directorJSONKeys.FirstName] = i[directorJSONKeys.FirstName] properties[directorJSONKeys.LastName] = i[directorJSONKeys.LastName] properties[directorJSONKeys.Name] = i[directorJSONKeys.Name] properties[directorJSONKeys.ImageUrl] = i[directorJSONKeys.ImageUrl] let director = Director(properties: properties) directors.append(director) } } } catch { throw MyAppErrors.ParsingError } return directors } public func directorshMoviesWithMethod(method: String, parameters: String, completionHandler: (director: [Director]?, error: ErrorType?) -> Void) -> NSURLSessionTask! { let session = NSURLSession.sharedSession() guard let url = NSURL(string: parameters) else { completionHandler(director: nil, error: MyAppErrors.InvalidUrlError) return nil } let request = NSURLRequest(URL: url) let task = session.dataTaskWithRequest(request) { data, response, error in if error != nil { completionHandler(director: nil, error: MyAppErrors.MovieSearchError) } else { do { let director = try self.getMoviesDirectorsFromJSON(data!) completionHandler(director: director, error: nil) } catch { completionHandler(director: nil, error: error) } } } task.resume() return task } public func downloadImageAtLocation(location: String, completionHandler: (imageData: NSData?, error: ErrorType?) -> Void) -> NSURLSessionTask! { let configuration = NSURLSessionConfiguration.defaultSessionConfiguration() let session = NSURLSession(configuration: configuration) guard let url = NSURL(string: location) else { completionHandler(imageData: nil, error: MyAppErrors.InvalidUrlError) return nil } let request = NSMutableURLRequest(URL: url) let task = session.dataTaskWithRequest(request) {data, response, error in if error != nil { completionHandler(imageData: nil, error: MyAppErrors.ImageDownloadError) } else { completionHandler(imageData: data, error: nil) } } task.resume() return task } InMyView  dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0)) { MyApp.sharedInstance().directorshMoviesWithMethod("", parameters: myUrl+"&dataFormat=json") {directors, error in if error != nil { dispatch_async(dispatch_get_main_queue()) { self.showAlert() } } else { dispatch_async(dispatch_get_main_queue()) { self.directors = directors! self.collectionView2.reloadData() } } } When using ;  @discardableResult Gives me error; Braced block of statements is an unused closure
You can annotate the method it is warning you about with @discardableResult. For example: @discardableResult func foobar() -> Bool { return true }